name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: npm install && npm run build-only

    # - name: Build and Deploy
    #   uses: JamesIves/github-pages-deploy-action@v4.6.3
    #   env:
    #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #     branch: main
    #     folder: docs
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs # The folder the action should deploy.
